# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/types.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ev1/types.proto\x12\x08proto.v1\"\xb3\x03\n\x0bHTTPRequest\x12\x12\n\x04\x62ody\x18\x01 \x01(\x0cR\x04\x62ody\x12\x16\n\x06method\x18\x02 \x01(\tR\x06method\x12\x10\n\x03url\x18\x03 \x01(\tR\x03url\x12\x1f\n\x0b\x65ndpoint_id\x18\x04 \x01(\tR\nendpointId\x12\x30\n\x03\x65nv\x18\x05 \x03(\x0b\x32\x1e.proto.v1.HTTPRequest.EnvEntryR\x03\x65nv\x12\x39\n\x06header\x18\x06 \x03(\x0b\x32!.proto.v1.HTTPRequest.HeaderEntryR\x06header\x12\x18\n\x07runtime\x18\x07 \x01(\tR\x07runtime\x12#\n\rdeployment_id\x18\x08 \x01(\tR\x0c\x64\x65ploymentId\x12\x0e\n\x02id\x18\t \x01(\tR\x02id\x1a\x36\n\x08\x45nvEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\x1aQ\n\x0bHeaderEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x16.proto.v1.HeaderFieldsR\x05value:\x02\x38\x01\"&\n\x0cHeaderFields\x12\x16\n\x06\x66ields\x18\x01 \x03(\tR\x06\x66ields\"\xe4\x01\n\x0cHTTPResponse\x12\x12\n\x04\x62ody\x18\x01 \x01(\x0cR\x04\x62ody\x12\x12\n\x04\x63ode\x18\x02 \x01(\x05R\x04\x63ode\x12\x1d\n\nrequest_id\x18\x03 \x01(\tR\trequestId\x12:\n\x06header\x18\x04 \x03(\x0b\x32\".proto.v1.HTTPResponse.HeaderEntryR\x06header\x1aQ\n\x0bHeaderEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x16.proto.v1.HeaderFieldsR\x05value:\x02\x38\x01\x42w\n\x0c\x63om.proto.v1B\nTypesProtoP\x01Z\x1agithub.com/hnimtadd/run/pb\xa2\x02\x03PXX\xaa\x02\x08Proto.V1\xca\x02\x08Proto\\V1\xe2\x02\x14Proto\\V1\\GPBMetadata\xea\x02\tProto::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\014com.proto.v1B\nTypesProtoP\001Z\032github.com/hnimtadd/run/pb\242\002\003PXX\252\002\010Proto.V1\312\002\010Proto\\V1\342\002\024Proto\\V1\\GPBMetadata\352\002\tProto::V1'
  _globals['_HTTPREQUEST_ENVENTRY']._loaded_options = None
  _globals['_HTTPREQUEST_ENVENTRY']._serialized_options = b'8\001'
  _globals['_HTTPREQUEST_HEADERENTRY']._loaded_options = None
  _globals['_HTTPREQUEST_HEADERENTRY']._serialized_options = b'8\001'
  _globals['_HTTPRESPONSE_HEADERENTRY']._loaded_options = None
  _globals['_HTTPRESPONSE_HEADERENTRY']._serialized_options = b'8\001'
  _globals['_HTTPREQUEST']._serialized_start=29
  _globals['_HTTPREQUEST']._serialized_end=464
  _globals['_HTTPREQUEST_ENVENTRY']._serialized_start=327
  _globals['_HTTPREQUEST_ENVENTRY']._serialized_end=381
  _globals['_HTTPREQUEST_HEADERENTRY']._serialized_start=383
  _globals['_HTTPREQUEST_HEADERENTRY']._serialized_end=464
  _globals['_HEADERFIELDS']._serialized_start=466
  _globals['_HEADERFIELDS']._serialized_end=504
  _globals['_HTTPRESPONSE']._serialized_start=507
  _globals['_HTTPRESPONSE']._serialized_end=735
  _globals['_HTTPRESPONSE_HEADERENTRY']._serialized_start=383
  _globals['_HTTPRESPONSE_HEADERENTRY']._serialized_end=464
# @@protoc_insertion_point(module_scope)
