version:  "3.0"
services:
  metadata-database:
    image: mongo:latest
    container_name: metadata_mongo
    networks:
      - raptor
    ports:
      - "27018:27017"
    volumes:
      - ./data/mongo:/data/db

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    networks:
      - raptor
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./data/minio:/data
      - ./config/minio/config.env:/etc/config.env:ro
    command: server /data --console-address :9001


networks:
  raptor:
    driver: bridge