version:  "3.0"
services:
  metadata-database:
    image: mongo:latest
    container_name: metadata_mongo
    networks:
      - raptor
    ports:
      - "27018:27017"
#    environment:


networks:
  raptor:
    driver: bridge