name: Go Build

on:
  push:
    braches:
      - "**"
  pull_request:
    braches:
      - "**"
jobs:
  build-server:
    name: Build Server
    runs-on: ubuntu-latest

  steps:
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"

    - name: Get Code
      uses: actions/checkout@v4

    - name: Build
      run: go build ./cmd/*

    - name: Build Wasm
      run: GOOS=wasip1 GOARCH=wasm go build -o test/go/data/main.wasm test/go/data/main.go
