name: Go CI

on:
  push:
    braches:
      - "**"
  pull_request:
    braches:
      - "**"
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  main:
    name: Lint and Test
    environment: development
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54

      - name: Build
        run: go build ./cmd/*
      - name: Build Wasm
        run: GOOS=wasip1 GOARCH=wasm go build -o examples/go/example.wasm examples/go/example.go
      - name: Test
        run: go test ./...
