name: Go Tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"
permissions:
  contents: read

jobs:
  main:
    name: Go test 
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: false

      - name: Build Wasm
        run: make build_example

      - name: Test
        run: ENV=CI make test