name: Go CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"
permissions:
  contents: read

jobs:
  main:
    name: Go Lint 
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: false

      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2

      - name: Lint by golangci-lint
        run: go list -f '{{.Dir}}/...' -m | xargs -n 1 sh -c 'golangci-lint run $0 || exit -1'
