name: Go CI

on:
  push:
    braches:
      - "**"
  pull_request:
    braches:
      - "**"
permissions:
  contents: read

jobs:
  main:
    name: Lint and Test
    environment: development
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: false

      - name: Build
        run: go build ./cmd/**/main.go

      - name: Build Wasm
        run: make build_example

      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2

      - name: Lint by golangci-lint
        run: go list -f '{{.Dir}}/...' -m | xargs -n 1 sh -c 'golangci-lint run $0 || exit -1'

      - name: Test
        run: go test ./...

