name: Go CI

on:
  push:
    braches:
      - "**"
  pull_request:
    braches:
      - "**"
permissions:
  contents: read

jobs:
  main:
    name: Lint and Test
    environment: development
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: false

      - name: Build
        run: go build ./cmd/*
      - name: Build Wasm
        run: make build_example

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
          args: --timeout=30m --config=.golangci.yml

      - name: Test
        run: go test ./...

